# Generated by Django 4.1.4 on 2022-12-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="preview",
            field=models.ImageField(default="", upload_to="media"),
            preserve_default=False,
        ),
    ]
